language: generic

matrix:
  include:
    - language: node_js
      node_js:
        - "node"

      env:
        - JOBNAME=ESLINT

      scripts:
        - npm run lint

    - language: node_js
      node_js:
        - "node"

      env:
        - JOBNAME=TESTS

      scripts:
        - npm run test --watchAll=false
